version: "3"
services:
 db:
  image: mysql:5.7
  ports:
    - '3306:3306'
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  volumes:
    - ./Autolab/docker/mysql:/etc/mysql/conf.d
    - db_data:/var/lib/mysql

 tango:
  build: ./Tango
  command: sh start.sh
  privileged: true

 web:
  build: ./Autolab
  ports:
    - '12301:80'
    - '12343:443'
  volumes:
    - autolab_courses:/home/app/webapp/courses
volumes:
  db_data:
  autolab_courses:

# slacker:
#  image: datamove/slacker
#  volumes: 
#    - /home/artem/slacker-config.yml:/etc/slacker/config.yml
#  environment:
#     PYTHONPATH: './'

